plugins {
    id 'java'
    id 'io.qameta.allure' version '4.1.0'
}

group = 'com.qa.automation'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_20
    targetCompatibility = JavaVersion.VERSION_20
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.microsoft.playwright:playwright:1.40.0'

    testImplementation 'io.cucumber:cucumber-java:7.14.0'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.14.0'
    testImplementation 'io.cucumber:cucumber-picocontainer:7.14.0'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
    testImplementation 'org.junit.platform:junit-platform-suite-api:1.10.0'
    testImplementation 'org.junit.platform:junit-platform-suite-engine:1.10.0'

    testImplementation 'io.qameta.allure:allure-cucumber7-jvm:2.25.0'
    testImplementation 'io.qameta.allure:allure-junit5:2.25.0'

    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'ch.qos.logback:logback-classic:1.4.12'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'io.github.bonigarcia:webdrivermanager:5.6.3'
    testImplementation 'org.assertj:assertj-core:3.24.1'
}

tasks {
    test {
        useJUnitPlatform()
        systemProperty 'cucumber.execution.parallel.enabled', 'true'
        systemProperty 'allure.results.directory', 'target/allure-results'
        testLogging {
            events 'passed', 'skipped', 'failed'
            exceptionFormat 'full'
        }
    }
}